[package]
name = "xxh3"
version = "0.3.1"
authors = []
edition = "2018"

[lib]
name = "xxh3"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.1"
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }
