[package]
name = "xxh3"
version = "0.3.4"
authors = []
edition = "2018"

[lib]
name = "xxh3"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.29.1"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }
